FROM gramineproject/gramine:latest AS builder

RUN apt-get update && \
    apt-get install -y python3-pip && \
    pip3 install numpy tensorflow

COPY . /app
WORKDIR /app

RUN gramine-sgx-pal-custom python3 -m pip install -r requirements.txt

RUN gramine-sgx-ias-verify --key /app/enclave-key.pem -d /app

FROM gramineproject/gramine:runtime
COPY --from=builder /app /app
CMD ["gramine-sgx", "python3", "app.py"]
