name: Deploy ShieldNet AI Defender

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      if: github.ref == 'refs/heads/main'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build Docker image
      run: docker build -t shieldnet-ai-defender .

    - name: Scan for vulnerabilities
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: shieldnet-ai-defender
        format: 'table'
        exit-code: '1'
        severity: 'CRITICAL,HIGH'

    - name: Push to Docker Hub
      if: github.ref == 'refs/heads/main'
      run: |
        docker tag shieldnet-ai-defender ${{ secrets.DOCKER_HUB_USERNAME }}/shieldnet-ai-defender:latest
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/shieldnet-ai-defender:latest
